# Generated by Django 5.2.2 on 2025-06-22 08:42

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('productname', models.CharField(max_length=100)),
                ('productcategory', models.CharField(choices=[('1', 'Electric Buses'), ('2,', 'Charging Equipment'), ('3', 'Spare Parts'), ('4', 'Accessories')], default='1', max_length=4)),
                ('stock', models.IntegerField(default=0)),
                ('productimg', models.ImageField(upload_to='static/productimg')),
                ('cost', models.IntegerField()),
                ('description', models.TextField()),
                ('launch', models.DateField(default=datetime.date.today)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
