# Generated by Django 4.2.20 on 2025-05-17 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_productcategory_product_productimg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='launch',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
