# Generated by Django 5.2.2 on 2025-06-22 08:42

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modelname', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('qty', models.IntegerField()),
                ('fromappointmentdate', models.DateField(null=True)),
                ('toappointmentdate', models.DateField(null=True)),
                ('location', models.CharField(max_length=50)),
                ('purpose', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConfirmedAppointment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('appointeddate', models.DateTimeField(default=datetime.datetime.today)),
                ('appointmentcompanyuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.appointmentmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
