# Generated by Django 5.2.2 on 2025-06-22 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentmodel',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='confirmedappointment',
            old_name='uuid',
            new_name='id',
        ),
    ]
