# Generated by Django 5.2.2 on 2025-06-30 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_rename_uuid_appointmentmodel_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentmodel',
            name='modelname',
        ),
        migrations.RemoveField(
            model_name='appointmentmodel',
            name='product',
        ),
        migrations.RemoveField(
            model_name='appointmentmodel',
            name='qty',
        ),
    ]
