# Generated by Django 5.2.2 on 2025-06-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_remove_appointmentmodel_modelname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentmodel',
            name='fullname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
