# Generated by Django 5.2.2 on 2025-06-10 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentmodel',
            name='vehicleimage',
        ),
    ]
