# Generated by Django 5.2.2 on 2025-06-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_appointmentmodel_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentmodel',
            name='purpose',
            field=models.CharField(choices=[('1', 'Consultaion'), ('1', 'Bussiness Meeting'), ('1', 'Other')], max_length=50),
        ),
    ]
