# Generated by Django 5.2.2 on 2025-06-22 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUserModelApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='governmentdetails',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='privatebussines',
            old_name='uuid',
            new_name='id',
        ),
    ]
